apiVersion: "batch/v2alpha1"
kind: CronJob
metadata:
  name: {{.Values.name}}
spec:
  schedule: {{.Values.schedule}}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{.Values.name}}
            image: {{.Values.image}}:{{.Values.tag}}
            args: ["--config", "/etc/config/config.yml", "/etc/config/action_file.yml"]
            volumeMounts:
              - name: config-volume
                mountPath: /etc/config
          volumes:
            - name: config-volume
              configMap:
                name: curator-config
          restartPolicy: OnFailure
